"""Public service contract for the RAG bounded context."""

from typing import Protocol

from assessment_app.services.rag.public.models import GraphVisualization, RagIngestionResult


class RagIngestionService(Protocol):
    """Public contract for rebuilding RAG ingestion data."""

    def rebuild(self) -> RagIngestionResult:
        """Rebuild parsed sections, graph maps, and vector records."""
        ...

    def get_graph_visualization(self, offset: int = 0, limit: int = 120) -> GraphVisualization:
        """Return graph data generated by ingestion for frontend visualization."""
        ...
