"""RAG ingestion rebuild route."""

from fastapi import APIRouter, Query
from pydantic import BaseModel

from assessment_app.config.dependencies import RagIngestionServiceDep

router = APIRouter()


class IngestResponse(BaseModel):
    """HTTP response for an ingestion rebuild."""

    section_count: int
    chunk_count: int
    graph_chunk_count: int
    vector_count: int


class GraphNodeResponse(BaseModel):
    id: str
    label: str
    kind: str
    parent_id: str | None
    section_id: str | None
    text_preview: str | None


class GraphEdgeResponse(BaseModel):
    source: str
    target: str
    kind: str


class GraphVisualizationResponse(BaseModel):
    sections_count: int
    chunks_count: int
    references_count: int
    total_nodes: int
    total_edges: int
    offset: int
    limit: int
    nodes: list[GraphNodeResponse]
    edges: list[GraphEdgeResponse]


@router.post("", response_model=IngestResponse)
async def rebuild_ingestion(service: RagIngestionServiceDep) -> IngestResponse:
    """Rebuild configured PDF ingestion data."""
    result = service.rebuild()
    return IngestResponse(**result.__dict__)


@router.get("/graph", response_model=GraphVisualizationResponse)
async def get_ingestion_graph(
    service: RagIngestionServiceDep,
    offset: int = Query(default=0, ge=0),
    limit: int = Query(default=5000, ge=1, le=5000),
) -> GraphVisualizationResponse:
    """Return stored graph data generated by ingestion."""
    graph = service.get_graph_visualization(offset=offset, limit=limit)
    return GraphVisualizationResponse(
        sections_count=graph.sections_count,
        chunks_count=graph.chunks_count,
        references_count=graph.references_count,
        total_nodes=graph.total_nodes,
        total_edges=graph.total_edges,
        offset=graph.offset,
        limit=graph.limit,
        nodes=[GraphNodeResponse(**node.__dict__) for node in graph.nodes],
        edges=[GraphEdgeResponse(**edge.__dict__) for edge in graph.edges],
    )
